### ISSUE TITLE
wrong command to start simple project

### ISSUE THREAD

**Issue by kkaarreell** [feedhenry/nodeschool#7]
In notebooks/Workshop.ipynb
Instead of 
`echo "console.log('Hello');\nconsole.log('World');\n" > index.js`
there should be 
`echo -e "console.log('Hello');\nconsole.log('World');\n" > index.js`

**Comment by AdamSaleh** [comment]
Couldn not reproduce? :-/

**Comment by kkaarreell** [comment]
???
Isn't the description clear enough? You must tell echo to interpret escape characters, otherwise you would get "\n" strings in the index.js file.

**Comment by AdamSaleh** [comment]
We managed to figure this out on our second run. You need to add in `-e` only if you are using bash/sh. When I and my colleague were reviewing this, both of us use zsh, that deals with the escapes, therefore we really didn't see the problem.

I will rechceck rest of our command-line examples in sh.
